/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <VREF.h>
#include <VREF_aliases.h>
#include <SENSOROUTPUT.h>
#include <SENSOROUTPUT_aliases.h>
#include <PGA_1.h>
#include <ADC_DelSig_1.h>
#include <Filter_1.h>
#include <Filter_1_PVT.h>
#include <VDAC8_1.h>
#include <LED1.h>
#include <LED1_aliases.h>
#include <GND.h>
#include <GND_aliases.h>
#include <VDAC8_2.h>
#include <LED2.h>
#include <LED2_aliases.h>
#include <isr_1.h>
#include <ADC_DelSig_1_AMux.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_IRQ.h>
#include <ADC_DelSig_1_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

